// Generated by CoffeeScript 1.6.2
(function() {
  describe("Meal", function() {
    beforeEach(function() {
      this.donut = new Dish('Maple Bacon Donut $1.99');
      return this.fish = new Dish('Salmon $14.25');
    });
    return describe("blank object", function() {
      beforeEach(function() {
        return this.meal = new Meal;
      });
      it("adds a new dish", function() {
        this.meal.add(this.donut);
        return (expect(this.meal.dishes.length)).toEqual(1);
      });
      return it("adds several dishes", function() {
        this.meal.add(this.donut, this.fish);
        return (expect(this.meal.dishes.length)).toEqual(2);
      });
    });
  });

}).call(this);
