// Generated by CoffeeScript 1.6.2
(function() {
  describe("Money", function() {
    describe("valid value", function() {
      beforeEach(function() {
        return this.money = new Money("25.99");
      });
      it("parses to cents", function() {
        return (expect(this.money.cents)).toEqual(2599);
      });
      it("formats to string", function() {
        return (expect(this.money.toString())).toEqual("$25.99");
      });
      return it("formats to string when cents is 0x", function() {
        var money2;

        money2 = new Money("25.09");
        return (expect(money2.toString())).toEqual("$25.09");
      });
    });
    return describe("invalid value", function() {
      return it("sets cents to 0 if a valid value cannot be parsed", function() {
        var money;

        money = new Money("No Mo Monies");
        return (expect(money.cents)).toEqual(0);
      });
    });
  });

}).call(this);
